"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var ACTION_PREFIX = 'queue-for-redux/';
exports.SUSPEND_SAGA = ACTION_PREFIX + "SUSPEND_SAGA";
exports.RETRY_ALL = ACTION_PREFIX + "RETRY_ALL";
exports.RETRY = ACTION_PREFIX + "RETRY";
exports.REMOVE = ACTION_PREFIX + "REMOVE";
exports.CONSUME = ACTION_PREFIX + "CONSUME";
exports.RESET = ACTION_PREFIX + "RESET";
exports.QUEUE_ACTION = ACTION_PREFIX + "QUEUE_ACTION";
exports.RESET_THROTTLE = ACTION_PREFIX + "RESET_THROTTLE";
