const ACTION_PREFIX = 'queue-for-redux/'

export const SUSPEND_SAGA = `${ACTION_PREFIX}SUSPEND_SAGA`
export const RETRY_ALL = `${ACTION_PREFIX}RETRY_ALL`
export const RETRY = `${ACTION_PREFIX}RETRY`
export const REMOVE = `${ACTION_PREFIX}REMOVE`
export const CONSUME = `${ACTION_PREFIX}CONSUME`
export const RESET = `${ACTION_PREFIX}RESET`
export const QUEUE_ACTION = `${ACTION_PREFIX}QUEUE_ACTION`
export const RESET_THROTTLE = `${ACTION_PREFIX}RESET_THROTTLE`
